[32mINFO    [0m hhj:my_log.py:39 ====所有用例的前置操作：启动对戏APP(setUp)====
[32mINFO    [0m hhj:my_log.py:39 _______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
[32mINFO    [0m hhj:my_log.py:39 <built-in method values of dict object at 0x0000027999FE6540>
[32mINFO    [0m hhj:my_log.py:39 ****正常用例——查看用户协议****
[32mINFO    [0m hhj:my_log.py:39 引导页_查看用户协议等待元素('accessibility id', '《用户协议》')可见
[32mINFO    [0m hhj:my_log.py:39 ('accessibility id', '《用户协议》')元素等待结束，等待时长为：0:00:02.136777毫秒
[32mINFO    [0m hhj:my_log.py:39 引导页_查看用户协议查找元素：('accessibility id', '《用户协议》')
[32mINFO    [0m hhj:my_log.py:39 引导页_查看用户协议_点击元素：('accessibility id', '《用户协议》')
[32mINFO    [0m hhj:my_log.py:39 引导页_查看用户协议等待元素('-android uiautomator', 'new UiSelector().descriptionContains("服务")')可见
[32mINFO    [0m hhj:my_log.py:39 ('-android uiautomator', 'new UiSelector().descriptionContains("服务")')元素等待结束，等待时长为：0:00:00.089281毫秒
[32mINFO    [0m hhj:my_log.py:39 引导页_查看用户协议查找元素：('-android uiautomator', 'new UiSelector().descriptionContains("服务")')
[32mINFO    [0m hhj:my_log.py:39 在引导页_查看用户协议中获取('-android uiautomator', 'new UiSelector().descriptionContains("服务")')元素_content-desc的属性值
[32mINFO    [0m hhj:my_log.py:39 引导页_查看用户协议查找元素：('-android uiautomator', 'new UiSelector().className("android.widget.ImageView")')
[31m[1mERROR   [0m hhj:my_log.py:47 引导页_查看用户协议查找元素('-android uiautomator', 'new UiSelector().className("android.widget.ImageView")')存在失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 106, in get_element
    return self.driver.find_element(*locator)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

[32mINFO    [0m hhj:my_log.py:39 截取网页成功，文件路径为：D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Outputs\ScreenShots\引导页_查看用户协议_2022-04-06 15-45-09.png
[32mINFO    [0m hhj:my_log.py:39 allure截取网页成功，文件路径为：引导页_查看用户协议